### PR TITLE
Fix/add ability to set pub sub decorators together

### PR DESCRIPTION
**Pull request by MaksimKiselev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [-] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [+] Tests for the changes have been added (for bug fixes / features)
- [-] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

This PR address this issue, that was initially evaluated as feature. https://github.com/flamewow/nestjs-asyncapi/issues/465
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: 465

## What is the new behavior?
AsyncApiPub and AsyncApiSub decorators now creates method decorator with different meta keys

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by flamewow** [comment]
@MaksimKiselev thanks for handling that thing
https://www.npmjs.com/package/nestjs-asyncapi/v/1.1.1

**Comment by Pedr0Rocha** [comment]
Any idea why my subs are returning an object instead of an array here after this change?
https://github.com/flamewow/nestjs-asyncapi/pull/473/files#diff-bc32787f3b434f34f1cf6480e670abbcd25092915b971c0f234579c24c8379b6R16

```
{
  '0': {
    channel: 'test',
    message: {
      payload: [Object],
      name: 'HealthController#getHealth',
      headers: undefined
    },
    type: 'sub'
  }
}
```

as a result I get this error:
```
const metadataCombined = [...metadataOperations || [], ...metadataSubs || [], ...metadataPubs || []];
                                                                           ^
TypeError: (metadataSubs || []) is not iterable
    at exploreAsyncApiOperationMetadata (/nestjs-asyncapi/dist/lib/explorers/asyncapi-operation.explorer.js:23:76)
```

I tried reproducing the same behaviour in the sample app but I couldn't, it returns an array as it should.

**Comment by MaksimKiselev** [comment]
@Pedr0Rocha are you build your nest app with tsc compiler?

Can you please provide your tsconfig* files, package.json (deps, devDeps)?

**Comment by Pedr0Rocha** [comment]
It was fixed here: https://github.com/flamewow/nestjs-asyncapi/pull/494/commits/5069e2210f5ecd8e87c35e4615c2a066b298252b

Thanks

**Pull request merged**
